services:
  webui:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./staging:/app/staging
      - ./deleted:/app/deleted
      - ./uploaded:/app/uploaded
    environment:
      MILVUS_HOST: milvus
      MILVUS_PORT: 19530
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: rag_metadata
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: secure_password
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
      OLLAMA_API_BASE: http://ollama:11434

  milvus:
    image: milvusdb/milvus:v2.4.13
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./databases/milvus/db:/var/lib/milvus
      - ./logs/milvus:/var/log/milvus
    environment:
      ETCD_USE_EMBED: true
      ETCD_DATA_DIR: /var/lib/milvus/etcd
      COMMON_STORAGETYPE: local
    command: ["milvus", "run", "standalone"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./databases/postgres:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    environment:
      POSTGRES_DB: rag_metadata
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./containers/ollama:/root/.ollama
      - ./logs/ollama:/var/log/ollama
    environment:
      OLLAMA_HOST: 0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
